server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location = /player.html {
        try_files /player.html =404;
        add_header Content-Security-Policy "frame-ancestors 'self' https://*.robbo.world https://scratch.ru http://localhost:3030 http://127.0.0.1:3030" always;
    }

    gzip on;
    gzip_types text/css application/javascript application/json image/svg+xml;
}
